version: '3.8'

volumes:
  datafiles:

services:
  www:
    build: .
    ports: 
        - "5000:80"
    volumes:
        - ./../:/var/www/html/
    links:
        - mysql
    networks:
        - default
    restart: always

  mysql:
    container_name: spoton
    image: mysql:8.0.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3000:3306"
    environment:
      - MYSQL_DATABASE=spoton
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - datafiles:/var/lib/mysql
      - ./db/spoton.sql:/docker-entrypoint-initdb.d/spoton.sql
    restart: always